CREATE TABLE [dbo].[Logs]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[LogGuid] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[LogDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[UserId] INT NOT NULL,
	[LogMessage] TEXT NOT NULL,
	[ErrorPage] NVARCHAR(75), 
    CONSTRAINT [AK_Logs_Guid] UNIQUE ([LogGuid]) 
)
